"""Generate a professional one-page research memo PDF."""

from __future__ import annotations
from pathlib import Path
from typing import Dict, Any
from datetime import datetime

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False

EXPORT_DIR = Path(__file__).parent.parent / "logs" / "memos"
EXPORT_DIR.mkdir(parents=True, exist_ok=True)


class MemoPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 8, "FinAgentVerse Research Memo", ln=True)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 5, "Multi-Agent Autonomous Financial Intelligence | HACKVERSE 2026", ln=True)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} | Page {self.page_no()}", align="C")


def export_research_memo(result: Dict[str, Any], profile_name: str) -> Path:
    if not HAS_FPDF:
        # Fallback text memo
        path = EXPORT_DIR / f"memo_{result.get('session_id', 'unknown')}.txt"
        path.write_text(_text_memo(result, profile_name))
        return path

    pdf = MemoPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    snap = result["market_snapshot"]
    syn = result["synthesis"]
    agents = result["agent_outputs"]

    # Title block
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"{snap['ticker']}  |  {syn['final_signal']}", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Price: Rs {snap['last_price']} ({snap['change_pct']:+.2f}%)  |  Confidence: {syn['confidence']:.0%}  |  Profile: {profile_name}", ln=True)
    pdf.ln(4)

    # Recommendation
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "Personalized Recommendation", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, syn.get("recommendation", ""))
    pdf.ln(3)

    # Agent summary table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "Agent Consensus", ln=True)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(55, 6, "Agent", border=1)
    pdf.cell(30, 6, "Signal", border=1)
    pdf.cell(25, 6, "Score", border=1)
    pdf.cell(25, 6, "Conf", border=1)
    pdf.cell(55, 6, "Key Factor", border=1, ln=True)
    pdf.set_font("Helvetica", "", 8)
    for a in agents:
        factor = (a.get("key_factors") or ["—"])[0][:40]
        pdf.cell(55, 5, a["agent_name"][:28], border=1)
        pdf.cell(30, 5, a["signal"], border=1)
        pdf.cell(25, 5, f"{a['score']:+.2f}", border=1)
        pdf.cell(25, 5, f"{a['confidence']:.0%}", border=1)
        pdf.cell(55, 5, factor, border=1, ln=True)
    pdf.ln(4)

    # Reasoning chain
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "Decision Reasoning Chain", ln=True)
    pdf.set_font("Helvetica", "", 9)
    for step in syn.get("reasoning_chain", [])[:8]:
        pdf.multi_cell(0, 4, f"- {step}")
    pdf.ln(3)

    # Citations
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "Source Attribution (RAG)", ln=True)
    pdf.set_font("Helvetica", "", 8)
    for a in agents:
        for c in a.get("citations", [])[:2]:
            pdf.multi_cell(0, 4, f"[{a['agent_name']}] {c.get('source', '')}: {c.get('snippet', '')[:120]}...")
    pdf.ln(3)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 4, "Disclaimer: This is an educational research memo generated by a multi-agent AI system for hackathon demonstration. Not investment advice. Past performance is not indicative of future results. Always do your own due diligence.")

    path = EXPORT_DIR / f"memo_{result.get('session_id', 'unknown')}.pdf"
    pdf.output(str(path))
    return path


def _text_memo(result: Dict[str, Any], profile_name: str) -> str:
    snap = result["market_snapshot"]
    syn = result["synthesis"]
    lines = [
        "FinAgentVerse Research Memo",
        f"Ticker: {snap['ticker']} | Signal: {syn['final_signal']} | Conf: {syn['confidence']:.0%}",
        f"Profile: {profile_name}",
        "",
        syn.get("recommendation", ""),
        "",
        "Reasoning:",
    ]
    for s in syn.get("reasoning_chain", []):
        lines.append(f"  {s}")
    return "\n".join(lines)
