/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAskRouteImport } from './routes/_app/ask'
import { Route as AppBriefingRouteImport } from './routes/_app/briefing'
import { Route as AppDeskRouteImport } from './routes/_app/desk'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppJudgesRouteImport } from './routes/_app/judges'
import { Route as AppPortfolioRouteImport } from './routes/_app/portfolio'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppBriefingRoute = AppBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AppRoute,
} as any)
const AppDeskRoute = AppDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppJudgesRoute = AppJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ask': typeof AppAskRoute
  '/briefing': typeof AppBriefingRoute
  '/desk': typeof AppDeskRoute
  '/history': typeof AppHistoryRoute
  '/judges': typeof AppJudgesRoute
  '/portfolio': typeof AppPortfolioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ask': typeof AppAskRoute
  '/briefing': typeof AppBriefingRoute
  '/desk': typeof AppDeskRoute
  '/history': typeof AppHistoryRoute
  '/judges': typeof AppJudgesRoute
  '/portfolio': typeof AppPortfolioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ask': typeof AppAskRoute
  '/_app/briefing': typeof AppBriefingRoute
  '/_app/desk': typeof AppDeskRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/judges': typeof AppJudgesRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ask'
    | '/briefing'
    | '/desk'
    | '/history'
    | '/judges'
    | '/portfolio'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ask'
    | '/briefing'
    | '/desk'
    | '/history'
    | '/judges'
    | '/portfolio'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ask'
    | '/_app/briefing'
    | '/_app/desk'
    | '/_app/history'
    | '/_app/judges'
    | '/_app/portfolio'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/briefing': {
      id: '/_app/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AppBriefingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/desk': {
      id: '/_app/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof AppDeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/judges': {
      id: '/_app/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof AppJudgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAskRoute: typeof AppAskRoute
  AppBriefingRoute: typeof AppBriefingRoute
  AppDeskRoute: typeof AppDeskRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppJudgesRoute: typeof AppJudgesRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAskRoute: AppAskRoute,
  AppBriefingRoute: AppBriefingRoute,
  AppDeskRoute: AppDeskRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppJudgesRoute: AppJudgesRoute,
  AppPortfolioRoute: AppPortfolioRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
